[tool.poetry]
name = "cgmodels"
version = "0.3.0"
description = "Models used at clinical genomics"
authors = ["moonso <mans.magnusson@scilifelab.se>"]
readme = "README.md"
homepage = "https://github.com/Clinical-Genomics/cgmodels"
repository = "https://github.com/Clinical-Genomics/cgmodels"

[tool.black]
line-length = 100

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "^1.7.3"
typing-extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
