[tool.poetry]
name = "agilicus"
version = "1.98.8"
description = "Agilicus SDK"
license = "MIT"
homepage = "https://www.agilicus.com/"
repository = "https://github.com/Agilicus"
authors = ["Agilicus Devs <dev@agilicus.com>"]
readme = "README.md"
include = [ "agilicus_README.md" ]

[tool.poetry.dependencies]
python = "^3.7"
certifi = ">=14.05.14"
python_dateutil = ">2.5.3"
PyJWT = "~2.0.1"
requests = ">=2.23.0,<2.24.0"
prettytable = ">=0.7.2,<0.8.0"
oauth2client = ">=4.1.3,<4.2.0"
click-shell = ">=2.0,<3.0"
six = "^1.14.0"
cryptography = "^3.1.1"


[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^20.8b1"
flake8 = "^3.7.9"
markdown = "^3.2.1"
ptvsd = "^4.3.2"
pre-commit = "^2.1.1"
safety = "^1.8.5"

[tool.poetry.scripts]
agilicus-cli = 'agilicus.main:main'

[tool.isort]
line_length = 89
# force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
not_skip = "__init__.py"
filter_files = true
exclude = 'agilicus/agilicus_api/**'


[tool.black]
line-length = 89
target-version = "1.98.8"
include = '\.pyi?$'
exclude = '''
    \.git
  | \.tox
  | \.venv
  | agilicus_api
  | build
  | dist
'''

# ignore = # E203, E266, E501, W503, F403, F401
[tool.flake8]
max-line-length = 89
exclude = 'agilicus/agilicus_api/**'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
