[tool.poetry]
name = "musamusa_etr"
version = "0.0.5"
description = "Easy To Read text format file"
authors = ["suizokukan <suizokukan@orange.fr>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
musamusa-errors = "^0.3"
musamusa-fal = "^0.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
