[tool.poetry]
name = "pybiolib"
version = "0.1.741"
description = "BioLib Python Client"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/biolib"
keywords=["biolib"]
authors = [
    "biolib <hello@biolib.com>",
]
classifiers = [
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ]
packages = [
    { include = "biolib" },
]
include = [
    "README.md",
    "LICENSE",
    "pyppeteer",
]

[tool.poetry.scripts]
biolib = "biolib:cli"

[tool.poetry.dependencies]
requests = "==2.24.0"
python = "^3.6.1"
aenum = "^2.2.3"
appdirs = "^1.4.3"
certifi = ">=2019.11.28"
ordered_set = "^4.0.1"
pyee = "^7.0.1"
tqdm = "^4.42.1"
typing_extensions = { version ="^3.7.4", python = "<3.8"}
typing_inspect = { version ="^0.5.0", python = "<3.8"}
websockets = "^8.1"
pyyaml = "==5.4.1"
docker = "==4.4.1"
nest_asyncio = "==1.4.0"
gunicorn = "==19.9.0"
flask = "==1.1.2"
flask-cors = "==3.0.10"
boto3 = "==1.16.53"
pycryptodome = "==3.9.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
