[tool.poetry]
name = "openqlab"
version = "0.3.4"
description = "An open-source collection of tools for quantum-optics experiments"
authors = [
"Jan Petermann <jpeterma@physnet.uni-hamburg.de>",
"Christian Darsow-Fromm <cdarsowf@physnet.uni-hamburg.de>",
]
maintainers = [
"Christian Darsow-Fromm <cdarsowf@physnet.uni-hamburg.de>",
"Jan Petermann <jpeterma@physnet.uni-hamburg.de>",
]
readme = "README.md"
repository = "https://gitlab.com/las-nq/openqlab"
documentation = "https://las-nq-serv.physnet.uni-hamburg.de/python/openqlab/"

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "^1.18.2"
matplotlib = "^3.2.1"
tabulate = "^0.8.7"
pathlib = "^1.0.1"
pyvisa-py = "^0.5.1"
scipy = "^1.4.1"
pandas = "~1.1"
importlib-metadata = {version = "^1.1.3", python = "<=3.7"}
dataclasses = { version="^0.7", python="^3.6, <3.7" }
typeguard = "^2.9.1"
PyVISA = "^1.11.1"
pyserial = "^3.5"
tables = "^3.6.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.7.9"
recommonmark = "^0.6.0"
docutils = "^0.16"
sphinx-markdown-tables = "^0.0.12"
pytest = "^6.1.2"
pytest-cov = "^2.8.1"
sphinx-rtd-theme = "^0.5.0"
twine = "^3.1.1"
mypy = "^0.790"
pylint = "^2.4.4"
sphinx = "^3.1"
pre-commit = "^2.2.0"
pydocstyle = "^5.0.2"
isort = "^4.3.21"
seed-isort-config = "^2.1.1"
ipython = "^7.13.0"
rope = "^0.16.0"
py2exe = "^0.9.2"  # Needed for tk on Windows
pydocstring = "^0.2.1"
tomlkit = "^0.7.0"
uncertainties = "^3.1.5"
ipdb = "^0.13.4"
jsonpickle = "^1.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --log-level=INFO --cov openqlab --cov-report term-missing  --no-cov-on-fail --cov-report=html"
testpaths = [
    "src/tests",
]

[tool.coverage]
    [tool.coverage.run]
    omit =[
        "*/_old_importers/*",
    ]
    [tool.coverage.report]
    fail_under = 94.8
    omit =[
        "src/openqlab/io/importers/keysight_binary.py"
    ]

    [tool.coverage.html]
    directory = "htmlcov"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
