[tool.poetry]
name = "ehelply-python-sdk"
version = "0.1.26"
description = ""
authors = ["Shawn Clake <shawn.clake@ehelply.com>"]
readme = "readme.md"
homepage = "https://ehelply.com"

[tool.poetry.dependencies]
python = "~3.8"
requests = "^2.23.0"
python-jose = {extras = ["cryptography"], version = "^3.1.0"}
pyjwt = "^1.7.1"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
cryptography = "^2.9.2"
pyopenssl = "^19.1.0"
typer = "^0.2.1"
python_dateutil = "^2.8.1"
python-slugify = "^4.0.0"
wheel = "^0.34.2"
ehelply-logger = "^0.0.8"
pytest-cov = "^2.10.1"
pytest-asyncio = "^0.14.0"
isodate = "^0.6.0"
pydantic = "^1.7.3"
pdoc3 = "^0.9.2"

[tool.poetry.scripts]
ehelply_sdk = 'ehelply_python_sdk.cli:cli_main'

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
