[tool.poetry]
name = "netbox_supervisor_plugin"
version = "0.1.1"
description = "An NetBox plugin to create Supervisor for Tenants"
authors = ["Ilya Zakharov"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
