[tool.poetry]
name = "qctrl"
version = "9.4.0"
description = "Q-CTRL Python"
license = "https://q-ctrl.com/terms"
authors = ["Q-CTRL <support@q-ctrl.com>"]
maintainers = ["Q-CTRL <support@q-ctrl.com>"]
readme = "DESCRIPTION.md"
homepage = "https://q-ctrl.com"
repository = ""
documentation = "https://docs.q-ctrl.com/references/python/qctrl"
keywords = [
    "q-ctrl",
    "qctrl",
    "quantum control"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Distributed Computing"
]
packages = [
    { include = "qctrl" },
]

[tool.poetry.dependencies]  # https://poetry.eustace.io/docs/versions
python = ">=3.6.4, <3.9"
numpy = ">=1.16.2"
tqdm = ">=4.30.0"
toml = "^0.10.0"
python-forge = "^18.6.0"
click = "^7.0"
gql = "3.0.0a4"
requests = "^2.23.0"
tenacity = "^6.0.0"
attrs = "^19.3.0"
cached-property = "^1.5.1"
commonmark = "~0.9.1"
pytz = "^2020.1"
qctrl-commons = "~5.0.0"
python-dateutil = "^2.8.1"
jsonschema = "^3.2.0"


[tool.poetry.dev-dependencies]
pytest-mock = "^1.4.0"
pytest = "^5.0.1"
pylama = "*"
pylint = "*"
pylint_runner = "*"
sphinx = "~3.2.1"
black = "^20.8b1"
sphinx-rtd-theme = "~0.4.3"
pytest-xdist = "^1.32.0"
isort = "^5.7.0"
pre-commit = "^2.9.3"
pytest-cov = "^2.10.1"

[tool.poetry.scripts]
qctrl = "qctrl.scripts:main"

[[tool.poetry.source]]
name = 'Q-CTRL PyPI'
url = 'https://pypi.q-ctrl.com/simple'

[tool.poetry.urls]
LinkedIn = "https://www.linkedin.com/company/q-ctrl/"
Facebook = "https://www.facebook.com/qctrl"
Twitter = "https://twitter.com/qctrlHQ"
YouTube = "https://www.youtube.com/c/qctrl"
GitHub = "https://github.com/qctrl"

[tool.black]
exclude = '''
(
    /(
        docs
    )/
    | setup.py
)
'''

[tool.isort]
profile = "black"
force_grid_wrap = "2"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
versioning = "pep"
prereleases = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

#  _______________________________________
# / If you update this file, please run   \
# \ poetry update && dephell deps convert /
#  ---------------------------------------
#        \   ^__^
#         \  (oo)\_______
#            (__)\       )\/\
#                ||----w |
#                ||     ||
