[tool.poetry]
name = "et-micc-build"
version = "1.1.4"
description = "CLI micc-build and module for building binary extensions created with micc."
authors = ["Engelbert Tijskens <engelbert.tijskens@uantwerpen.be>"]
license = "MIT"

readme = 'README.rst'

repository = "https://github.com/etijskens/et-micc-build"
homepage = "https://github.com/etijskens/et-micc-build"

keywords = ['packaging', 'poetry']

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.17.0"
et-micc = "1.1.4"
pybind11 = "^2.6.1"

[tool.poetry.dev-dependencies]
pytest = "^4.4.2"

[tool.poetry.scripts]
micc-build = "et_micc_build:cli_micc_build.main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
