[tool.poetry]
name = 'nav-dcat'
version = '0.1.7'
description = ''
authors = ['NAV IT dataplattform']
license = 'MIT'

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.1"
pytest = "^6.2.1"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
