[tool.poetry]
name = "fairlay"
version = "0.1.2"
description = "Fairlay Client for Python 3.8+"
authors = ["jim zhou <43537315+jimtje@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pycryptodome = "^3.10.1"
requests = "^2.25.1"
ujson = "^4.0.2"
arrow = "^1.0.3"
httpx = "^0.17.1"
marshmallow = "^3.10.0"
marshmallow-enum = "^1.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
