[tool.poetry]
name = "sanic-rest"
version = "1.2.0a3"
description = "Sanic Rest Framework with Google Cloud Datastore"
authors = ["Joao Daher <joao@daher.dev>"]
repository = "https://github.com/flamingo-run/sanic-rest"
readme = "README.md"
keywords = ["sanic", "restful", "datastore"]
packages = [
    { include = "sanic_rest" },
]


[tool.poetry.dependencies]
python = ">=3.8,<3.10"
sanic = "*"
sanic-openapi = "*"
gcp-pilot = { version = "*", extras = ["datastore", "storage"]}
sanic-jwt = { version = "*", optional = true }
passlib = { version = "*", optional = true }
argon2_cffi = { version = "*", optional = true }


[tool.poetry.extras]
auth = ["sanic-jwt", "passlib", "argon2_cffi"]


[tool.poetry.dev-dependencies]
pylint = "*"
nose = "*"
coverage = "*"


[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
