[tool.poetry]
name = "graiax-sayamod-record"
version = "0.2.3"
description = "A graiax saya mod to record message in databases."
authors = ["hans <dxzenghan@163.com>"]
license = "AGPL-3.0 License"

[tool.poetry.dependencies]
python = "^3.8"
graia-application-mirai = "0.16.1"
graia-broadcast = "^0.7.0"
pony = "^0.7.14"
graia-saya = "^0.0.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
