[tool.poetry]
name = "postgres_azure_certificate_auth"
version = "1.0.1"
description = "Functions for connecting to a Postgres database using certificate authentication stored in Azure Key Vault"
authors = ["peder2911 <pedlan@prio.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
psycopg2 = "^2.8.6"
compose = "^1.1.1"
azure-identity = "^1.5.0"
azure-keyvault-secrets = "^4.2.0"
azure-appconfiguration = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
